"""Fix FK types and create relations tables

Revision ID: 1552d1a212d7
Revises: 1b1f3a2e03a8
Create Date: 2025-11-24 14:14:24.757691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1552d1a212d7'
down_revision = '1b1f3a2e03a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('detection_department',
    sa.Column('detection_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.PrimaryKeyConstraint('detection_id', 'department_id')
    )
    op.create_table('detection_tag',
    sa.Column('detection_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('detection_id', 'tag_id')
    )
    op.create_table('image',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_filename', sa.String(), nullable=True),
    sa.Column('annotated_filename', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.alter_column('detection_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.alter_column('detection_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.drop_table('image')
    op.drop_table('detection_tag')
    op.drop_table('detection_department')
    op.drop_table('tag')
    op.drop_table('department')
    # ### end Alembic commands ###
