"""Add detections merged table

Revision ID: 1b1f3a2e03a8
Revises: a0e3f544ba8d
Create Date: 2025-11-21 12:04:46.339894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b1f3a2e03a8'
down_revision = 'a0e3f544ba8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('detection_type', sa.String(length=20), nullable=False),
    sa.Column('image_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pothole_severity', sa.String(length=20), nullable=True),
    sa.Column('waste_category', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('detection_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wastes')
    op.drop_table('potholes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potholes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('detected_image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('potholes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('potholes_pkey'))
    )
    op.create_table('wastes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('detected_image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('detection_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_waste', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('waste_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_recyclable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_decomposable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('wastes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wastes_pkey'))
    )
    op.drop_table('detections')
    # ### end Alembic commands ###
